---
title: "cmdmystery"
author: "Yue Li"
date: "9/21/2017"
output:
  # pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Get the Clues
First we follow the instructions to get the clues for this task. The instruction suggestes us to find the word 'CLUE' in crimescene.

```{bash}
cd /Users/yueli/Desktop/2017\ Fall/course/36750/assignments-yuelicmu/cmdmurder/clmystery 
## cat instructions
grep 'CLUE' mystery/crimescene > clues.txt
cat clues.txt
```
## Find Annabel
The third clue provides useful information to us. We need to find a woman with name Annabel. So we search for Annabel in the people file.
```{bash}
cd /Users/yueli/Desktop/2017\ Fall/course/36750/assignments-yuelicmu/cmdmurder/clmystery
grep 'Annabel' mystery/people > annabel.txt
cat annabel.txt
```
There are two female Annabels. We can find them according to the Street and line information, then printing out the results.
```{bash}
cd /Users/yueli/Desktop/2017\ Fall/course/36750/assignments-yuelicmu/cmdmurder/clmystery
head -n 40 mystery/streets/Hart_Place | tail -n 1
head -n 179 mystery/streets/Buckingham_Place | tail -n 1
```
Then we have the interview number. Looking at the interview information respectively:
```{bash}
cd /Users/yueli/Desktop/2017\ Fall/course/36750/assignments-yuelicmu/cmdmurder/clmystery
cat mystery/interviews/interview-47246024
cat mystery/interviews/interview-699607
```
## Find the Car
The second interview is useful to us. Then we should find the car with liscence plate starting with 'L337' and ending with '9'; also it should be 'Blue' and 'Honda'. Besides the height of the owner should be more than 6. After making sure there is no person taller than 7', we can just serach for word 'Height: 6'. We use simple regular expressions to serch for liscence:
```{bash}
cd /Users/yueli/Desktop/2017\ Fall/course/36750/assignments-yuelicmu/cmdmurder/clmystery
grep -A 4 'License Plate L337.*9' mystery/vehicles | grep -A 3 -B 1 'Honda' | grep -B 2 -A 2 'Blue' > L3379
grep -B 1 'Height: 6' L3379 | grep 'Owner:' > name
sed 's/Owner: //' name > name1
cat name1
```
We find four such cars. Then we can use the second clue. The killer's name should exist in all the membership files of AAA, Delta SkyMiles, the local library and the Museum of Bash History. The serch goes like this:
```{bash}
cd /Users/yueli/Desktop/2017\ Fall/course/36750/assignments-yuelicmu/cmdmurder/clmystery
grep -Ff name1 mystery/memberships/AAA | grep -Ff mystery/memberships/Delta_SkyMiles | grep -Ff mystery/memberships/Terminal_City_Library | grep -Ff mystery/memberships/Museum_of_Bash_History
```
## The Killer
Two names remain. The only thing we have not checked yet is that the killer is a man; so we print the information for these two names:
```{bash}
cd /Users/yueli/Desktop/2017\ Fall/course/36750/assignments-yuelicmu/cmdmurder/clmystery
grep 'Jacqui Maher' mystery/people
grep 'Jeremy Bowers' mystery/people
```
So the killer is **Jeremy Bowers**.
